# Generated by Django 3.1.2 on 2020-11-18 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201118_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 18, 18, 8, 41, 822078, tzinfo=utc)),
        ),
    ]
