# Generated by Django 3.1.2 on 2020-11-18 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201118_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 18, 18, 13, 58, 355928, tzinfo=utc)),
        ),
    ]
